events {}

http {
    resolver 127.0.0.11 valid=10s;

    upstream node_apps {
        zone node_apps 64k;
        server app:3000 resolve;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://node_apps;
        }
    }
}